const t = [
  { name: "No Goalscorer", first: ["15", "2"] },
  [
    [
      { name: "Armando Broja" },
      { match: "Chelsea v Man City" },
      { first: [["8", "1"]] },
      { anytime: [["10", "3"]] },
      { last: [["8", "1"]] },
      { two_or_more: [["22", "1"]] },
      { hattrick: [["150", "1"]] },
      { first_and_last: [["22", "1"]] },
      { first_or_last: [["5", "1"]] },
    ],
    [
      { name: "Nicolas Jackson" },
      { match: "Chelsea v Man City" },
      { first: [["17", "2"]] },
      { anytime: [["16", "5"]] },
      { last: [["15", "2"]] },
      { two_or_more: [["22", "1"]] },
      { hattrick: [["125", "1"]] },
      { first_and_last: [["22", "1"]] },
      { first_or_last: [["5", "1"]] },
    ],
    [
      { name: "Deivid Washington" },
      { match: "Chelsea v Man City" },
      { first: [["9", "1"]] },
      { anytime: [["4", "1"]] },
      { last: [["9", "1"]] },
      { two_or_more: [["33", "1"]] },
      { hattrick: [["200", "1"]] },
      { first_and_last: [["28", "1"]] },
      { first_or_last: [["13", "2"]] },
    ],
    [
      { name: "Cole Palmer" },
      { match: "Chelsea v Man City" },
      { first: [["9", "1"]] },
      { anytime: [["4", "1"]] },
      { last: [["9", "1"]] },
      { two_or_more: [["28", "1"]] },
      { hattrick: [["200", "1"]] },
      { first_and_last: [["28", "1"]] },
      { first_or_last: [["13", "2"]] },
    ],
    [
      { name: "Raheem Sterling" },
      { match: "Chelsea v Man City" },
      { first: [["9", "1"]] },
      { anytime: [["7", "2"]] },
      { last: [["17", "2"]] },
      { two_or_more: [["25", "1"]] },
      { hattrick: [["150", "1"]] },
      { first_and_last: [["25", "1"]] },
      { first_or_last: [["11", "2"]] },
    ],
    [
      { name: "Noni Madueke" },
      { match: "Chelsea v Man City" },
      { first: [["11", "1"]] },
      { anytime: [["5", "1"]] },
      { last: [["11", "1"]] },
      { two_or_more: [["40", "1"]] },
      { hattrick: [["250", "1"]] },
      { first_and_last: [["35", "1"]] },
      { first_or_last: [["8", "1"]] },
    ],
    [
      { name: "Mykhaylo Mudryk" },
      { match: "Chelsea v Man City" },
      { first: [["12", "1"]] },
      { anytime: [["24", "5"]] },
      { last: [["11", "1"]] },
      { two_or_more: [["40", "1"]] },
      { hattrick: [["250", "1"]] },
      { first_and_last: [["35", "1"]] },
      { first_or_last: [["15", "2"]] },
    ],
    [
      { name: "Alex Matos" },
      { match: "Chelsea v Man City" },
      { first: [["12", "1"]] },
      { anytime: [["6", "1"]] },
      { last: [["12", "1"]] },
      { two_or_more: [["50", "1"]] },
      { hattrick: [["300", "1"]] },
      { first_and_last: [["40", "1"]] },
      { first_or_last: [["9", "1"]] },
    ],
    [
      { name: "Conor Gallagher" },
      { match: "Chelsea v Man City" },
      { first: [["16", "1"]] },
      { anytime: [["15", "2"]] },
      { last: [["16", "1"]] },
      { two_or_more: [["70", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["50", "1"]] },
      { first_or_last: [["11", "1"]] },
    ],
    [
      { name: "Enzo Fernandez" },
      { match: "Chelsea v Man City" },
      { first: [["20", "1"]] },
      { anytime: [["10", "1"]] },
      { last: [["20", "1"]] },
      { two_or_more: [["100", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["60", "1"]] },
      { first_or_last: [["14", "1"]] },
    ],
    [
      { name: "Ian Maatsen" },
      { match: "Chelsea v Man City" },
      { first: [["22", "1"]] },
      { anytime: [["11", "1"]] },
      { last: [["22", "1"]] },
      { two_or_more: [["125", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["66", "1"]] },
      { first_or_last: [["16", "1"]] },
    ],
    [
      { name: "Reece James" },
      { match: "Chelsea v Man City" },
      { first: [["22", "1"]] },
      { anytime: [["10", "1"]] },
      { last: [["22", "1"]] },
      { two_or_more: [["125", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["60", "1"]] },
      { first_or_last: [["14", "1"]] },
    ],
    [
      { name: "Moises Caicedo" },
      { match: "Chelsea v Man City" },
      { first: [["28", "1"]] },
      { anytime: [["14", "1"]] },
      { last: [["28", "1"]] },
      { two_or_more: [["200", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["90", "1"]] },
      { first_or_last: [["18", "1"]] },
    ],
    [
      { name: "Lesley Ugochukwu" },
      { match: "Chelsea v Man City" },
      { first: [["33", "1"]] },
      { anytime: [["14", "1"]] },
      { last: [["33", "1"]] },
      { two_or_more: [["200", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["90", "1"]] },
      { first_or_last: [["20", "1"]] },
    ],
    [
      { name: "Levi Colwill" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["18", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["125", "1"]] },
      { first_or_last: [["25", "1"]] },
    ],
    [
      { name: "Benoit Badiashile" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["18", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["125", "1"]] },
      { first_or_last: [["25", "1"]] },
    ],
    [
      { name: "Thiago Silva" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["18", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["125", "1"]] },
      { first_or_last: [["25", "1"]] },
    ],
    [
      { name: "Malo Gusto" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["18", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["125", "1"]] },
      { first_or_last: [["25", "1"]] },
    ],
    [
      { name: "Axel Disasi" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["16", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["100", "1"]] },
      { first_or_last: [["22", "1"]] },
    ],
    [
      { name: "Marc Cucurella" },
      { match: "Chelsea v Man City" },
      { first: [["50", "1"]] },
      { anytime: [["22", "1"]] },
      { last: [["50", "1"]] },
      { two_or_more: [["400", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["150", "1"]] },
      { first_or_last: [["35", "1"]] },
    ],
    [
      { name: "Erling Haaland" },
      { match: "Chelsea v Man City" },
      { first: [["3", "1"]] },
      { anytime: [["17", "20"]] },
      { last: [["14", "5"]] },
      { two_or_more: [["9", "2"]] },
      { hattrick: [["16", "1"]] },
      { first_and_last: [["15", "2"]] },
      { first_or_last: [["29", "20"]] },
    ],
    [
      { name: "Julian Alvarez" },
      { match: "Chelsea v Man City" },
      { first: [["6", "1"]] },
      { anytime: [["21", "10"]] },
      { last: [["11", "2"]] },
      { two_or_more: [["12", "1"]] },
      { hattrick: [["55", "1"]] },
      { first_and_last: [["16", "1"]] },
      { first_or_last: [["16", "5"]] },
    ],
    [
      { name: "Jeremy Doku" },
      { match: "Chelsea v Man City" },
      { first: [["17", "2"]] },
      { anytime: [["3", "1"]] },
      { last: [["15", "2"]] },
      { two_or_more: [["20", "1"]] },
      { hattrick: [["125", "1"]] },
      { first_and_last: [["22", "1"]] },
      { first_or_last: [["24", "5"]] },
    ],
    [
      { name: "Phil Foden" },
      { match: "Chelsea v Man City" },
      { first: [["17", "2"]] },
      { anytime: [["3", "1"]] },
      { last: [["15", "2"]] },
      { two_or_more: [["20", "1"]] },
      { hattrick: [["125", "1"]] },
      { first_and_last: [["22", "1"]] },
      { first_or_last: [["9", "2"]] },
    ],
    [
      { name: "Oscar Bobb" },
      { match: "Chelsea v Man City" },
      { first: [["17", "2"]] },
      { anytime: [["18", "5"]] },
      { last: [["17", "2"]] },
      { two_or_more: [["25", "1"]] },
      { hattrick: [["200", "1"]] },
      { first_and_last: [["25", "1"]] },
      { first_or_last: [["11", "2"]] },
    ],
    [
      { name: "Bernardo Silva" },
      { match: "Chelsea v Man City" },
      { first: [["10", "1"]] },
      { anytime: [["24", "5"]] },
      { last: [["10", "1"]] },
      { two_or_more: [["40", "1"]] },
      { hattrick: [["250", "1"]] },
      { first_and_last: [["33", "1"]] },
      { first_or_last: [["7", "1"]] },
    ],
    [
      { name: "Jack Grealish" },
      { match: "Chelsea v Man City" },
      { first: [["10", "1"]] },
      { anytime: [["19", "5"]] },
      { last: [["9", "1"]] },
      { two_or_more: [["28", "1"]] },
      { hattrick: [["200", "1"]] },
      { first_and_last: [["28", "1"]] },
      { first_or_last: [["6", "1"]] },
    ],
    [
      { name: "Matheus Nunes" },
      { match: "Chelsea v Man City" },
      { first: [["12", "1"]] },
      { anytime: [["6", "1"]] },
      { last: [["12", "1"]] },
      { two_or_more: [["50", "1"]] },
      { hattrick: [["300", "1"]] },
      { first_and_last: [["40", "1"]] },
      { first_or_last: [["9", "1"]] },
    ],
    [
      { name: "Rodri" },
      { match: "Chelsea v Man City" },
      { first: [["12", "1"]] },
      { anytime: [["6", "1"]] },
      { last: [["12", "1"]] },
      { two_or_more: [["50", "1"]] },
      { hattrick: [["300", "1"]] },
      { first_and_last: [["40", "1"]] },
      { first_or_last: [["9", "1"]] },
    ],
    [
      { name: "Mateo Kovacic" },
      { match: "Chelsea v Man City" },
      { first: [["14", "1"]] },
      { anytime: [["7", "1"]] },
      { last: [["14", "1"]] },
      { two_or_more: [["60", "1"]] },
      { hattrick: [["400", "1"]] },
      { first_and_last: [["45", "1"]] },
      { first_or_last: [["10", "1"]] },
    ],
    [
      { name: "Rico Lewis" },
      { match: "Chelsea v Man City" },
      { first: [["22", "1"]] },
      { anytime: [["11", "1"]] },
      { last: [["22", "1"]] },
      { two_or_more: [["125", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["65", "1"]] },
      { first_or_last: [["14", "1"]] },
    ],
    [
      { name: "John Stones" },
      { match: "Chelsea v Man City" },
      { first: [["22", "1"]] },
      { anytime: [["11", "1"]] },
      { last: [["22", "1"]] },
      { two_or_more: [["125", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["65", "1"]] },
      { first_or_last: [["14", "1"]] },
    ],
    [
      { name: "Kalvin Phillips" },
      { match: "Chelsea v Man City" },
      { first: [["25", "1"]] },
      { anytime: [["12", "1"]] },
      { last: [["25", "1"]] },
      { two_or_more: [["150", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["70", "1"]] },
      { first_or_last: [["16", "1"]] },
    ],
    [
      { name: "Nathan Ake" },
      { match: "Chelsea v Man City" },
      { first: [["25", "1"]] },
      { anytime: [["12", "1"]] },
      { last: [["25", "1"]] },
      { two_or_more: [["150", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["70", "1"]] },
      { first_or_last: [["16", "1"]] },
    ],
    [
      { name: "Ruben Dias" },
      { match: "Chelsea v Man City" },
      { first: [["33", "1"]] },
      { anytime: [["16", "1"]] },
      { last: [["33", "1"]] },
      { two_or_more: [["200", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["90", "1"]] },
      { first_or_last: [["20", "1"]] },
    ],
    [
      { name: "Josko Gvardiol" },
      { match: "Chelsea v Man City" },
      { first: [["33", "1"]] },
      { anytime: [["16", "1"]] },
      { last: [["33", "1"]] },
      { two_or_more: [["200", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["90", "1"]] },
      { first_or_last: [["20", "1"]] },
    ],
    [
      { name: "Manuel Akanji" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["16", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["100", "1"]] },
      { first_or_last: [["22", "1"]] },
    ],
    [
      { name: "Kyle Walker" },
      { match: "Chelsea v Man City" },
      { first: [["50", "1"]] },
      { anytime: [["20", "1"]] },
      { last: [["50", "1"]] },
      { two_or_more: [["300", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["150", "1"]] },
      { first_or_last: [["28", "1"]] },
    ],
  ],
];

console.log(t.length);
