const t = [
  { name: "No Goalscorer", first: ["15", "2"] },
  [
    [
      { name: "Armando Broja" },
      { match: "Chelsea v Man City" },
      { first: [["8", "1"]] },
      { anytime: [["10", "3"]] },
      { last: [["8", "1"]] },
      { two_or_more: [["22", "1"]] },
      { hattrick: [["150", "1"]] },
      { first_and_last: [["22", "1"]] },
      { first_or_last: [["5", "1"]] },
    ],
    [
      { name: "Nicolas Jackson" },
      { match: "Chelsea v Man City" },
      { first: [["17", "2"]] },
      { anytime: [["16", "5"]] },
      { last: [["15", "2"]] },
      { two_or_more: [["22", "1"]] },
      { hattrick: [["125", "1"]] },
      { first_and_last: [["22", "1"]] },
      { first_or_last: [["5", "1"]] },
    ],
    [
      { name: "Deivid Washington" },
      { match: "Chelsea v Man City" },
      { first: [["9", "1"]] },
      { anytime: [["4", "1"]] },
      { last: [["9", "1"]] },
      { two_or_more: [["33", "1"]] },
      { hattrick: [["200", "1"]] },
      { first_and_last: [["28", "1"]] },
      { first_or_last: [["13", "2"]] },
    ],
    [
      { name: "Cole Palmer" },
      { match: "Chelsea v Man City" },
      { first: [["9", "1"]] },
      { anytime: [["4", "1"]] },
      { last: [["9", "1"]] },
      { two_or_more: [["28", "1"]] },
      { hattrick: [["200", "1"]] },
      { first_and_last: [["28", "1"]] },
      { first_or_last: [["13", "2"]] },
    ],
    [
      { name: "Raheem Sterling" },
      { match: "Chelsea v Man City" },
      { first: [["9", "1"]] },
      { anytime: [["7", "2"]] },
      { last: [["17", "2"]] },
      { two_or_more: [["25", "1"]] },
      { hattrick: [["150", "1"]] },
      { first_and_last: [["25", "1"]] },
      { first_or_last: [["11", "2"]] },
    ],
    [
      { name: "Noni Madueke" },
      { match: "Chelsea v Man City" },
      { first: [["11", "1"]] },
      { anytime: [["5", "1"]] },
      { last: [["11", "1"]] },
      { two_or_more: [["40", "1"]] },
      { hattrick: [["250", "1"]] },
      { first_and_last: [["35", "1"]] },
      { first_or_last: [["8", "1"]] },
    ],
    [
      { name: "Mykhaylo Mudryk" },
      { match: "Chelsea v Man City" },
      { first: [["12", "1"]] },
      { anytime: [["24", "5"]] },
      { last: [["11", "1"]] },
      { two_or_more: [["40", "1"]] },
      { hattrick: [["250", "1"]] },
      { first_and_last: [["35", "1"]] },
      { first_or_last: [["15", "2"]] },
    ],
    [
      { name: "Alex Matos" },
      { match: "Chelsea v Man City" },
      { first: [["12", "1"]] },
      { anytime: [["6", "1"]] },
      { last: [["12", "1"]] },
      { two_or_more: [["50", "1"]] },
      { hattrick: [["300", "1"]] },
      { first_and_last: [["40", "1"]] },
      { first_or_last: [["9", "1"]] },
    ],
    [
      { name: "Conor Gallagher" },
      { match: "Chelsea v Man City" },
      { first: [["16", "1"]] },
      { anytime: [["15", "2"]] },
      { last: [["16", "1"]] },
      { two_or_more: [["70", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["50", "1"]] },
      { first_or_last: [["11", "1"]] },
    ],
    [
      { name: "Enzo Fernandez" },
      { match: "Chelsea v Man City" },
      { first: [["20", "1"]] },
      { anytime: [["10", "1"]] },
      { last: [["20", "1"]] },
      { two_or_more: [["100", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["60", "1"]] },
      { first_or_last: [["14", "1"]] },
    ],
    [
      { name: "Ian Maatsen" },
      { match: "Chelsea v Man City" },
      { first: [["22", "1"]] },
      { anytime: [["11", "1"]] },
      { last: [["22", "1"]] },
      { two_or_more: [["125", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["66", "1"]] },
      { first_or_last: [["16", "1"]] },
    ],
    [
      { name: "Reece James" },
      { match: "Chelsea v Man City" },
      { first: [["22", "1"]] },
      { anytime: [["10", "1"]] },
      { last: [["22", "1"]] },
      { two_or_more: [["125", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["60", "1"]] },
      { first_or_last: [["14", "1"]] },
    ],
    [
      { name: "Moises Caicedo" },
      { match: "Chelsea v Man City" },
      { first: [["28", "1"]] },
      { anytime: [["14", "1"]] },
      { last: [["28", "1"]] },
      { two_or_more: [["200", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["90", "1"]] },
      { first_or_last: [["18", "1"]] },
    ],
    [
      { name: "Lesley Ugochukwu" },
      { match: "Chelsea v Man City" },
      { first: [["33", "1"]] },
      { anytime: [["14", "1"]] },
      { last: [["33", "1"]] },
      { two_or_more: [["200", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["90", "1"]] },
      { first_or_last: [["20", "1"]] },
    ],
    [
      { name: "Levi Colwill" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["18", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["125", "1"]] },
      { first_or_last: [["25", "1"]] },
    ],
    [
      { name: "Benoit Badiashile" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["18", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["125", "1"]] },
      { first_or_last: [["25", "1"]] },
    ],
    [
      { name: "Thiago Silva" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["18", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["125", "1"]] },
      { first_or_last: [["25", "1"]] },
    ],
    [
      { name: "Malo Gusto" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["18", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["125", "1"]] },
      { first_or_last: [["25", "1"]] },
    ],
    [
      { name: "Axel Disasi" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["16", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["100", "1"]] },
      { first_or_last: [["22", "1"]] },
    ],
    [
      { name: "Marc Cucurella" },
      { match: "Chelsea v Man City" },
      { first: [["50", "1"]] },
      { anytime: [["22", "1"]] },
      { last: [["50", "1"]] },
      { two_or_more: [["400", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["150", "1"]] },
      { first_or_last: [["35", "1"]] },
    ],
    [
      { name: "Erling Haaland" },
      { match: "Chelsea v Man City" },
      { first: [["3", "1"]] },
      { anytime: [["17", "20"]] },
      { last: [["14", "5"]] },
      { two_or_more: [["9", "2"]] },
      { hattrick: [["16", "1"]] },
      { first_and_last: [["15", "2"]] },
      { first_or_last: [["29", "20"]] },
    ],
    [
      { name: "Julian Alvarez" },
      { match: "Chelsea v Man City" },
      { first: [["6", "1"]] },
      { anytime: [["21", "10"]] },
      { last: [["11", "2"]] },
      { two_or_more: [["12", "1"]] },
      { hattrick: [["55", "1"]] },
      { first_and_last: [["16", "1"]] },
      { first_or_last: [["16", "5"]] },
    ],
    [
      { name: "Jeremy Doku" },
      { match: "Chelsea v Man City" },
      { first: [["17", "2"]] },
      { anytime: [["3", "1"]] },
      { last: [["15", "2"]] },
      { two_or_more: [["20", "1"]] },
      { hattrick: [["125", "1"]] },
      { first_and_last: [["22", "1"]] },
      { first_or_last: [["24", "5"]] },
    ],
    [
      { name: "Phil Foden" },
      { match: "Chelsea v Man City" },
      { first: [["17", "2"]] },
      { anytime: [["3", "1"]] },
      { last: [["15", "2"]] },
      { two_or_more: [["20", "1"]] },
      { hattrick: [["125", "1"]] },
      { first_and_last: [["22", "1"]] },
      { first_or_last: [["9", "2"]] },
    ],
    [
      { name: "Oscar Bobb" },
      { match: "Chelsea v Man City" },
      { first: [["17", "2"]] },
      { anytime: [["18", "5"]] },
      { last: [["17", "2"]] },
      { two_or_more: [["25", "1"]] },
      { hattrick: [["200", "1"]] },
      { first_and_last: [["25", "1"]] },
      { first_or_last: [["11", "2"]] },
    ],
    [
      { name: "Bernardo Silva" },
      { match: "Chelsea v Man City" },
      { first: [["10", "1"]] },
      { anytime: [["24", "5"]] },
      { last: [["10", "1"]] },
      { two_or_more: [["40", "1"]] },
      { hattrick: [["250", "1"]] },
      { first_and_last: [["33", "1"]] },
      { first_or_last: [["7", "1"]] },
    ],
    [
      { name: "Jack Grealish" },
      { match: "Chelsea v Man City" },
      { first: [["10", "1"]] },
      { anytime: [["19", "5"]] },
      { last: [["9", "1"]] },
      { two_or_more: [["28", "1"]] },
      { hattrick: [["200", "1"]] },
      { first_and_last: [["28", "1"]] },
      { first_or_last: [["6", "1"]] },
    ],
    [
      { name: "Matheus Nunes" },
      { match: "Chelsea v Man City" },
      { first: [["12", "1"]] },
      { anytime: [["6", "1"]] },
      { last: [["12", "1"]] },
      { two_or_more: [["50", "1"]] },
      { hattrick: [["300", "1"]] },
      { first_and_last: [["40", "1"]] },
      { first_or_last: [["9", "1"]] },
    ],
    [
      { name: "Rodri" },
      { match: "Chelsea v Man City" },
      { first: [["12", "1"]] },
      { anytime: [["6", "1"]] },
      { last: [["12", "1"]] },
      { two_or_more: [["50", "1"]] },
      { hattrick: [["300", "1"]] },
      { first_and_last: [["40", "1"]] },
      { first_or_last: [["9", "1"]] },
    ],
    [
      { name: "Mateo Kovacic" },
      { match: "Chelsea v Man City" },
      { first: [["14", "1"]] },
      { anytime: [["7", "1"]] },
      { last: [["14", "1"]] },
      { two_or_more: [["60", "1"]] },
      { hattrick: [["400", "1"]] },
      { first_and_last: [["45", "1"]] },
      { first_or_last: [["10", "1"]] },
    ],
    [
      { name: "Rico Lewis" },
      { match: "Chelsea v Man City" },
      { first: [["22", "1"]] },
      { anytime: [["11", "1"]] },
      { last: [["22", "1"]] },
      { two_or_more: [["125", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["65", "1"]] },
      { first_or_last: [["14", "1"]] },
    ],
    [
      { name: "John Stones" },
      { match: "Chelsea v Man City" },
      { first: [["22", "1"]] },
      { anytime: [["11", "1"]] },
      { last: [["22", "1"]] },
      { two_or_more: [["125", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["65", "1"]] },
      { first_or_last: [["14", "1"]] },
    ],
    [
      { name: "Kalvin Phillips" },
      { match: "Chelsea v Man City" },
      { first: [["25", "1"]] },
      { anytime: [["12", "1"]] },
      { last: [["25", "1"]] },
      { two_or_more: [["150", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["70", "1"]] },
      { first_or_last: [["16", "1"]] },
    ],
    [
      { name: "Nathan Ake" },
      { match: "Chelsea v Man City" },
      { first: [["25", "1"]] },
      { anytime: [["12", "1"]] },
      { last: [["25", "1"]] },
      { two_or_more: [["150", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["70", "1"]] },
      { first_or_last: [["16", "1"]] },
    ],
    [
      { name: "Ruben Dias" },
      { match: "Chelsea v Man City" },
      { first: [["33", "1"]] },
      { anytime: [["16", "1"]] },
      { last: [["33", "1"]] },
      { two_or_more: [["200", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["90", "1"]] },
      { first_or_last: [["20", "1"]] },
    ],
    [
      { name: "Josko Gvardiol" },
      { match: "Chelsea v Man City" },
      { first: [["33", "1"]] },
      { anytime: [["16", "1"]] },
      { last: [["33", "1"]] },
      { two_or_more: [["200", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["90", "1"]] },
      { first_or_last: [["20", "1"]] },
    ],
    [
      { name: "Manuel Akanji" },
      { match: "Chelsea v Man City" },
      { first: [["40", "1"]] },
      { anytime: [["16", "1"]] },
      { last: [["40", "1"]] },
      { two_or_more: [["250", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["100", "1"]] },
      { first_or_last: [["22", "1"]] },
    ],
    [
      { name: "Kyle Walker" },
      { match: "Chelsea v Man City" },
      { first: [["50", "1"]] },
      { anytime: [["20", "1"]] },
      { last: [["50", "1"]] },
      { two_or_more: [["300", "1"]] },
      { hattrick: [["500", "1"]] },
      { first_and_last: [["150", "1"]] },
      { first_or_last: [["28", "1"]] },
    ],
  ],
];

console.log(t.length);

var h = [
  [
    {
      name: "Ollie Watkins",
      match: "Aston Villa v Fulham",
      first: [["4", "1"]],
      anytime: [["19", "20"]],
      last: [["10", "3"]],
      two_or_more: [["5", "1"]],
      hattrick: [["18", "1"]],
      first_and_last: [["9", "1"]],
      first_or_last: [["17", "10"]],
    },
    {
      name: "Moussa Diaby",
      match: "Aston Villa v Fulham",
      first: [["11", "2"]],
      anytime: [["8", "5"]],
      last: [["9", "2"]],
      two_or_more: [["9", "1"]],
      hattrick: [["40", "1"]],
      first_and_last: [["14", "1"]],
      first_or_last: [["13", "5"]],
    },
    {
      name: "Jhon Duran",
      match: "Aston Villa v Fulham",
      first: [["11", "2"]],
      anytime: [["19", "10"]],
      last: [["11", "2"]],
      two_or_more: [["12", "1"]],
      hattrick: [["50", "1"]],
      first_and_last: [["16", "1"]],
      first_or_last: [["16", "5"]],
    },
    {
      name: "Bertrand Traore",
      match: "Aston Villa v Fulham",
      first: [["13", "2"]],
      anytime: [["23", "10"]],
      last: [["13", "2"]],
      two_or_more: [["14", "1"]],
      hattrick: [["70", "1"]],
      first_and_last: [["20", "1"]],
      first_or_last: [["19", "5"]],
    },
    {
      name: "Leon Bailey",
      match: "Aston Villa v Fulham",
      first: [["7", "1"]],
      anytime: [["11", "5"]],
      last: [["6", "1"]],
      two_or_more: [["14", "1"]],
      hattrick: [["60", "1"]],
      first_and_last: [["18", "1"]],
      first_or_last: [["18", "5"]],
    },
    {
      name: "Tommi O'Reilly",
      match: "Aston Villa v Fulham",
      first: [["8", "1"]],
      anytime: [["16", "5"]],
      last: [["8", "1"]],
      two_or_more: [["22", "1"]],
      hattrick: [["150", "1"]],
      first_and_last: [["28", "1"]],
      first_or_last: [["11", "2"]],
    },
    {
      name: "Douglas Luiz",
      match: "Aston Villa v Fulham",
      first: [["8", "1"]],
      anytime: [["29", "10"]],
      last: [["15", "2"]],
      two_or_more: [["18", "1"]],
      hattrick: [["125", "1"]],
      first_and_last: [["25", "1"]],
      first_or_last: [["24", "5"]],
    },
    {
      name: "Omari Kellyman",
      match: "Aston Villa v Fulham",
      first: [["9", "1"]],
      anytime: [["7", "2"]],
      last: [["9", "1"]],
      two_or_more: [["25", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["28", "1"]],
      first_or_last: [["6", "1"]],
    },
    {
      name: "Nicolo Zaniolo",
      match: "Aston Villa v Fulham",
      first: [["9", "1"]],
      anytime: [["3", "1"]],
      last: [["8", "1"]],
      two_or_more: [["20", "1"]],
      hattrick: [["125", "1"]],
      first_and_last: [["25", "1"]],
      first_or_last: [["5", "1"]],
    },
    {
      name: "John McGinn",
      match: "Aston Villa v Fulham",
      first: [["10", "1"]],
      anytime: [["4", "1"]],
      last: [["10", "1"]],
      two_or_more: [["33", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["35", "1"]],
      first_or_last: [["7", "1"]],
    },
    {
      name: "Youri Tielemans",
      match: "Aston Villa v Fulham",
      first: [["10", "1"]],
      anytime: [["9", "2"]],
      last: [["10", "1"]],
      two_or_more: [["35", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["7", "1"]],
    },
    {
      name: "Tim Iroegbunam",
      match: "Aston Villa v Fulham",
      first: [["14", "1"]],
      anytime: [["13", "2"]],
      last: [["14", "1"]],
      two_or_more: [["55", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["10", "1"]],
    },
    {
      name: "Leander Dendoncker",
      match: "Aston Villa v Fulham",
      first: [["14", "1"]],
      anytime: [["13", "2"]],
      last: [["14", "1"]],
      two_or_more: [["55", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["10", "1"]],
    },
    {
      name: "Matthew Cash",
      match: "Aston Villa v Fulham",
      first: [["16", "1"]],
      anytime: [["7", "1"]],
      last: [["16", "1"]],
      two_or_more: [["65", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["55", "1"]],
      first_or_last: [["11", "1"]],
    },
    {
      name: "Alex Moreno",
      match: "Aston Villa v Fulham",
      first: [["18", "1"]],
      anytime: [["17", "2"]],
      last: [["18", "1"]],
      two_or_more: [["80", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["60", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Ezri Konsa",
      match: "Aston Villa v Fulham",
      first: [["22", "1"]],
      anytime: [["10", "1"]],
      last: [["22", "1"]],
      two_or_more: [["125", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Diego Carlos",
      match: "Aston Villa v Fulham",
      first: [["25", "1"]],
      anytime: [["11", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Pau Torres",
      match: "Aston Villa v Fulham",
      first: [["25", "1"]],
      anytime: [["11", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Calum Chambers",
      match: "Aston Villa v Fulham",
      first: [["25", "1"]],
      anytime: [["11", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Lucas Digne",
      match: "Aston Villa v Fulham",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Clement Lenglet",
      match: "Aston Villa v Fulham",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Boubacar Kamara",
      match: "Aston Villa v Fulham",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Carlos Vinicius",
      match: "Aston Villa v Fulham",
      first: [["10", "1"]],
      anytime: [["16", "5"]],
      last: [["17", "2"]],
      two_or_more: [["22", "1"]],
      hattrick: [["150", "1"]],
      first_and_last: [["28", "1"]],
      first_or_last: [["11", "2"]],
    },
    {
      name: "Willian",
      match: "Aston Villa v Fulham",
      first: [["10", "1"]],
      anytime: [["9", "2"]],
      last: [["10", "1"]],
      two_or_more: [["33", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["35", "1"]],
      first_or_last: [["7", "1"]],
    },
    {
      name: "Rodrigo Muniz",
      match: "Aston Villa v Fulham",
      first: [["10", "1"]],
      anytime: [["7", "2"]],
      last: [["9", "1"]],
      two_or_more: [["25", "1"]],
      hattrick: [["150", "1"]],
      first_and_last: [["28", "1"]],
      first_or_last: [["11", "2"]],
    },
    {
      name: "Raul Jimenez",
      match: "Aston Villa v Fulham",
      first: [["10", "1"]],
      anytime: [["17", "5"]],
      last: [["17", "2"]],
      two_or_more: [["22", "1"]],
      hattrick: [["150", "1"]],
      first_and_last: [["28", "1"]],
      first_or_last: [["11", "2"]],
    },
    {
      name: "Harry Wilson",
      match: "Aston Villa v Fulham",
      first: [["11", "1"]],
      anytime: [["24", "5"]],
      last: [["11", "1"]],
      two_or_more: [["40", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["15", "2"]],
    },
    {
      name: "Bobby De Cordova-Reid",
      match: "Aston Villa v Fulham",
      first: [["12", "1"]],
      anytime: [["19", "5"]],
      last: [["9", "1"]],
      two_or_more: [["28", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["33", "1"]],
      first_or_last: [["13", "2"]],
    },
    {
      name: "Adama Traore",
      match: "Aston Villa v Fulham",
      first: [["12", "1"]],
      anytime: [["6", "1"]],
      last: [["12", "1"]],
      two_or_more: [["45", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Andreas Pereira",
      match: "Aston Villa v Fulham",
      first: [["12", "1"]],
      anytime: [["6", "1"]],
      last: [["12", "1"]],
      two_or_more: [["50", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Alex Iwobi",
      match: "Aston Villa v Fulham",
      first: [["12", "1"]],
      anytime: [["6", "1"]],
      last: [["12", "1"]],
      two_or_more: [["50", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Joao Palhinha",
      match: "Aston Villa v Fulham",
      first: [["14", "1"]],
      anytime: [["7", "1"]],
      last: [["14", "1"]],
      two_or_more: [["60", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["10", "1"]],
    },
    {
      name: "Sasa Lukic",
      match: "Aston Villa v Fulham",
      first: [["16", "1"]],
      anytime: [["15", "2"]],
      last: [["16", "1"]],
      two_or_more: [["65", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["55", "1"]],
      first_or_last: [["11", "1"]],
    },
    {
      name: "Tom Cairney",
      match: "Aston Villa v Fulham",
      first: [["18", "1"]],
      anytime: [["8", "1"]],
      last: [["18", "1"]],
      two_or_more: [["80", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["60", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Harrison Reed",
      match: "Aston Villa v Fulham",
      first: [["20", "1"]],
      anytime: [["9", "1"]],
      last: [["20", "1"]],
      two_or_more: [["100", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["66", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Timothy Castagne",
      match: "Aston Villa v Fulham",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Antonee Robinson",
      match: "Aston Villa v Fulham",
      first: [["50", "1"]],
      anytime: [["20", "1"]],
      last: [["50", "1"]],
      two_or_more: [["300", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["33", "1"]],
    },
    {
      name: "Devan Tanton",
      match: "Aston Villa v Fulham",
      first: [["50", "1"]],
      anytime: [["20", "1"]],
      last: [["50", "1"]],
      two_or_more: [["300", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["28", "1"]],
    },
    {
      name: "Calvin Bassey",
      match: "Aston Villa v Fulham",
      first: [["50", "1"]],
      anytime: [["20", "1"]],
      last: [["50", "1"]],
      two_or_more: [["300", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["28", "1"]],
    },
    {
      name: "Tosin Adarabioyo",
      match: "Aston Villa v Fulham",
      first: [["50", "1"]],
      anytime: [["20", "1"]],
      last: [["50", "1"]],
      two_or_more: [["300", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["28", "1"]],
    },
    {
      name: "Luc De Fougerolles",
      match: "Aston Villa v Fulham",
      first: [["66", "1"]],
      anytime: [["25", "1"]],
      last: [["66", "1"]],
      two_or_more: [["400", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["40", "1"]],
    },
    {
      name: "Tim Ream",
      match: "Aston Villa v Fulham",
      first: [["66", "1"]],
      anytime: [["25", "1"]],
      last: [["66", "1"]],
      two_or_more: [["400", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["40", "1"]],
    },
    {
      name: "Kenny Tete",
      match: "Aston Villa v Fulham",
      first: [["66", "1"]],
      anytime: [["22", "1"]],
      last: [["66", "1"]],
      two_or_more: [["300", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["35", "1"]],
    },
    {
      name: "Fode Ballo-Toure",
      match: "Aston Villa v Fulham",
      first: [["66", "1"]],
      anytime: [["25", "1"]],
      last: [["66", "1"]],
      two_or_more: [["400", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["40", "1"]],
    },
    { name: "No Goalscorer", first: ["10", "1"] },
  ],
  [
    {
      name: "Evan Ferguson",
      match: "Brighton v Sheffield Utd",
      first: [["4", "1"]],
      anytime: [["EVS"]],
      last: [["7", "2"]],
      two_or_more: [["11", "2"]],
      hattrick: [["20", "1"]],
      first_and_last: [["12", "1"]],
      first_or_last: [["2", "1"]],
    },
    {
      name: "Ansu Fati",
      match: "Brighton v Sheffield Utd",
      first: [["9", "2"]],
      anytime: [["13", "10"]],
      last: [["9", "2"]],
      two_or_more: [["15", "2"]],
      hattrick: [["28", "1"]],
      first_and_last: [["14", "1"]],
      first_or_last: [["5", "2"]],
    },
    {
      name: "Joao Pedro",
      match: "Brighton v Sheffield Utd",
      first: [["9", "2"]],
      anytime: [["5", "4"]],
      last: [["9", "2"]],
      two_or_more: [["7", "1"]],
      hattrick: [["28", "1"]],
      first_and_last: [["14", "1"]],
      first_or_last: [["12", "5"]],
    },
    {
      name: "Kaoru Mitoma",
      match: "Brighton v Sheffield Utd",
      first: [["11", "2"]],
      anytime: [["29", "20"]],
      last: [["5", "1"]],
      two_or_more: [["8", "1"]],
      hattrick: [["35", "1"]],
      first_and_last: [["16", "1"]],
      first_or_last: [["27", "10"]],
    },
    {
      name: "Simon Adingra",
      match: "Brighton v Sheffield Utd",
      first: [["6", "1"]],
      anytime: [["7", "4"]],
      last: [["11", "2"]],
      two_or_more: [["10", "1"]],
      hattrick: [["45", "1"]],
      first_and_last: [["18", "1"]],
      first_or_last: [["16", "5"]],
    },
    {
      name: "Joshua Duffus",
      match: "Brighton v Sheffield Utd",
      first: [["6", "1"]],
      anytime: [["2", "1"]],
      last: [["6", "1"]],
      two_or_more: [["12", "1"]],
      hattrick: [["50", "1"]],
      first_and_last: [["22", "1"]],
      first_or_last: [["18", "5"]],
    },
    {
      name: "Facundo Buonanotte",
      match: "Brighton v Sheffield Utd",
      first: [["13", "2"]],
      anytime: [["11", "5"]],
      last: [["13", "2"]],
      two_or_more: [["14", "1"]],
      hattrick: [["60", "1"]],
      first_and_last: [["25", "1"]],
      first_or_last: [["4", "1"]],
    },
    {
      name: "Pascal Gross",
      match: "Brighton v Sheffield Utd",
      first: [["15", "2"]],
      anytime: [["21", "10"]],
      last: [["13", "2"]],
      two_or_more: [["14", "1"]],
      hattrick: [["60", "1"]],
      first_and_last: [["22", "1"]],
      first_or_last: [["19", "5"]],
    },
    {
      name: "Adam Lallana",
      match: "Brighton v Sheffield Utd",
      first: [["8", "1"]],
      anytime: [["14", "5"]],
      last: [["8", "1"]],
      two_or_more: [["18", "1"]],
      hattrick: [["100", "1"]],
      first_and_last: [["33", "1"]],
      first_or_last: [["5", "1"]],
    },
    {
      name: "Jack Hinshelwood",
      match: "Brighton v Sheffield Utd",
      first: [["11", "1"]],
      anytime: [["9", "2"]],
      last: [["11", "1"]],
      two_or_more: [["35", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["8", "1"]],
    },
    {
      name: "Mahmoud Dahoud",
      match: "Brighton v Sheffield Utd",
      first: [["14", "1"]],
      anytime: [["6", "1"]],
      last: [["14", "1"]],
      two_or_more: [["50", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["55", "1"]],
      first_or_last: [["10", "1"]],
    },
    {
      name: "Carlos Baleba",
      match: "Brighton v Sheffield Utd",
      first: [["16", "1"]],
      anytime: [["13", "2"]],
      last: [["16", "1"]],
      two_or_more: [["55", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["60", "1"]],
      first_or_last: [["11", "1"]],
    },
    {
      name: "Billy Gilmour",
      match: "Brighton v Sheffield Utd",
      first: [["16", "1"]],
      anytime: [["13", "2"]],
      last: [["16", "1"]],
      two_or_more: [["55", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["60", "1"]],
      first_or_last: [["11", "1"]],
    },
    {
      name: "Adam Webster",
      match: "Brighton v Sheffield Utd",
      first: [["18", "1"]],
      anytime: [["15", "2"]],
      last: [["18", "1"]],
      two_or_more: [["66", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Pervis Estupinan",
      match: "Brighton v Sheffield Utd",
      first: [["18", "1"]],
      anytime: [["8", "1"]],
      last: [["18", "1"]],
      two_or_more: [["70", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Jan Paul van Hecke",
      match: "Brighton v Sheffield Utd",
      first: [["20", "1"]],
      anytime: [["17", "2"]],
      last: [["20", "1"]],
      two_or_more: [["80", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Lewis Dunk",
      match: "Brighton v Sheffield Utd",
      first: [["20", "1"]],
      anytime: [["17", "2"]],
      last: [["20", "1"]],
      two_or_more: [["80", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "James Milner",
      match: "Brighton v Sheffield Utd",
      first: [["22", "1"]],
      anytime: [["9", "1"]],
      last: [["22", "1"]],
      two_or_more: [["90", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Tariq Lamptey",
      match: "Brighton v Sheffield Utd",
      first: [["22", "1"]],
      anytime: [["10", "1"]],
      last: [["22", "1"]],
      two_or_more: [["100", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Joel Veltman",
      match: "Brighton v Sheffield Utd",
      first: [["25", "1"]],
      anytime: [["11", "1"]],
      last: [["25", "1"]],
      two_or_more: [["125", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Igor Julio",
      match: "Brighton v Sheffield Utd",
      first: [["33", "1"]],
      anytime: [["12", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "William Osula",
      match: "Brighton v Sheffield Utd",
      first: [["11", "1"]],
      anytime: [["4", "1"]],
      last: [["11", "1"]],
      two_or_more: [["33", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["15", "2"]],
    },
    {
      name: "Benie Traore",
      match: "Brighton v Sheffield Utd",
      first: [["12", "1"]],
      anytime: [["9", "2"]],
      last: [["12", "1"]],
      two_or_more: [["35", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["8", "1"]],
    },
    {
      name: "Oli McBurnie",
      match: "Brighton v Sheffield Utd",
      first: [["12", "1"]],
      anytime: [["15", "4"]],
      last: [["10", "1"]],
      two_or_more: [["25", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["13", "2"]],
    },
    {
      name: "Cameron Archer",
      match: "Brighton v Sheffield Utd",
      first: [["12", "1"]],
      anytime: [["7", "2"]],
      last: [["9", "1"]],
      two_or_more: [["22", "1"]],
      hattrick: [["150", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["6", "1"]],
    },
    {
      name: "James McAtee",
      match: "Brighton v Sheffield Utd",
      first: [["12", "1"]],
      anytime: [["5", "1"]],
      last: [["12", "1"]],
      two_or_more: [["40", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["17", "2"]],
    },
    {
      name: "Ryan One",
      match: "Brighton v Sheffield Utd",
      first: [["16", "1"]],
      anytime: [["13", "2"]],
      last: [["16", "1"]],
      two_or_more: [["55", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["60", "1"]],
      first_or_last: [["11", "1"]],
    },
    {
      name: "Gustavo Hamer",
      match: "Brighton v Sheffield Utd",
      first: [["16", "1"]],
      anytime: [["9", "2"]],
      last: [["11", "1"]],
      two_or_more: [["35", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["15", "2"]],
    },
    {
      name: "Andre Brooks",
      match: "Brighton v Sheffield Utd",
      first: [["20", "1"]],
      anytime: [["17", "2"]],
      last: [["20", "1"]],
      two_or_more: [["90", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Anis Ben Slimane",
      match: "Brighton v Sheffield Utd",
      first: [["20", "1"]],
      anytime: [["8", "1"]],
      last: [["20", "1"]],
      two_or_more: [["70", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Oliver Norwood",
      match: "Brighton v Sheffield Utd",
      first: [["25", "1"]],
      anytime: [["10", "1"]],
      last: [["25", "1"]],
      two_or_more: [["125", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Anel Ahmedhodzic",
      match: "Brighton v Sheffield Utd",
      first: [["28", "1"]],
      anytime: [["11", "1"]],
      last: [["28", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "John Fleck",
      match: "Brighton v Sheffield Utd",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Ben Osborn",
      match: "Brighton v Sheffield Utd",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Jayden Bogle",
      match: "Brighton v Sheffield Utd",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Auston Trusty",
      match: "Brighton v Sheffield Utd",
      first: [["40", "1"]],
      anytime: [["16", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Vinicius Souza",
      match: "Brighton v Sheffield Utd",
      first: [["40", "1"]],
      anytime: [["14", "1"]],
      last: [["40", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Yasser Larouci",
      match: "Brighton v Sheffield Utd",
      first: [["40", "1"]],
      anytime: [["16", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Max Lowe",
      match: "Brighton v Sheffield Utd",
      first: [["40", "1"]],
      anytime: [["16", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "George Baldock",
      match: "Brighton v Sheffield Utd",
      first: [["40", "1"]],
      anytime: [["14", "1"]],
      last: [["40", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Jili Buyabu",
      match: "Brighton v Sheffield Utd",
      first: [["50", "1"]],
      anytime: [["20", "1"]],
      last: [["50", "1"]],
      two_or_more: [["300", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["33", "1"]],
    },
    {
      name: "Jack Robinson",
      match: "Brighton v Sheffield Utd",
      first: [["50", "1"]],
      anytime: [["20", "1"]],
      last: [["50", "1"]],
      two_or_more: [["300", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["33", "1"]],
    },
    {
      name: "Femi Seriki",
      match: "Brighton v Sheffield Utd",
      first: [["66", "1"]],
      anytime: [["22", "1"]],
      last: [["66", "1"]],
      two_or_more: [["400", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["40", "1"]],
    },
    {
      name: "Luke Thomas",
      match: "Brighton v Sheffield Utd",
      first: [["66", "1"]],
      anytime: [["22", "1"]],
      last: [["66", "1"]],
      two_or_more: [["400", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["40", "1"]],
    },
    { name: "No Goalscorer", first: ["14", "1"] },
  ],
  [
    {
      name: "Mohamed Salah",
      match: "Liverpool v Brentford",
      first: [["7", "2"]],
      anytime: [["10", "11"]],
      last: [["7", "2"]],
      two_or_more: [["24", "5"]],
      hattrick: [["18", "1"]],
      first_and_last: [["12", "1"]],
      first_or_last: [["9", "5"]],
    },
    {
      name: "Darwin Nunez",
      match: "Liverpool v Brentford",
      first: [["9", "2"]],
      anytime: [["23", "20"]],
      last: [["4", "1"]],
      two_or_more: [["13", "2"]],
      hattrick: [["25", "1"]],
      first_and_last: [["14", "1"]],
      first_or_last: [["11", "5"]],
    },
    {
      name: "Diogo Jota",
      match: "Liverpool v Brentford",
      first: [["5", "1"]],
      anytime: [["6", "4"]],
      last: [["5", "1"]],
      two_or_more: [["17", "2"]],
      hattrick: [["35", "1"]],
      first_and_last: [["16", "1"]],
      first_or_last: [["14", "5"]],
    },
    {
      name: "Cody Gakpo",
      match: "Liverpool v Brentford",
      first: [["6", "1"]],
      anytime: [["6", "5"]],
      last: [["4", "1"]],
      two_or_more: [["13", "2"]],
      hattrick: [["25", "1"]],
      first_and_last: [["14", "1"]],
      first_or_last: [["9", "4"]],
    },
    {
      name: "Luis Diaz",
      match: "Liverpool v Brentford",
      first: [["6", "1"]],
      anytime: [["8", "5"]],
      last: [["5", "1"]],
      two_or_more: [["9", "1"]],
      hattrick: [["40", "1"]],
      first_and_last: [["18", "1"]],
      first_or_last: [["29", "10"]],
    },
    {
      name: "Ben Doak",
      match: "Liverpool v Brentford",
      first: [["6", "1"]],
      anytime: [["9", "5"]],
      last: [["6", "1"]],
      two_or_more: [["11", "1"]],
      hattrick: [["45", "1"]],
      first_and_last: [["20", "1"]],
      first_or_last: [["10", "3"]],
    },
    {
      name: "Harvey Elliott",
      match: "Liverpool v Brentford",
      first: [["10", "1"]],
      anytime: [["4", "1"]],
      last: [["10", "1"]],
      two_or_more: [["28", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["7", "1"]],
    },
    {
      name: "Dominik Szoboszlai",
      match: "Liverpool v Brentford",
      first: [["10", "1"]],
      anytime: [["19", "5"]],
      last: [["10", "1"]],
      two_or_more: [["28", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["7", "1"]],
    },
    {
      name: "Curtis Jones",
      match: "Liverpool v Brentford",
      first: [["11", "1"]],
      anytime: [["9", "2"]],
      last: [["11", "1"]],
      two_or_more: [["33", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["15", "2"]],
    },
    {
      name: "Wataru Endo",
      match: "Liverpool v Brentford",
      first: [["12", "1"]],
      anytime: [["11", "2"]],
      last: [["12", "1"]],
      two_or_more: [["45", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["55", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "James McConnell",
      match: "Liverpool v Brentford",
      first: [["12", "1"]],
      anytime: [["9", "2"]],
      last: [["12", "1"]],
      two_or_more: [["35", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["8", "1"]],
    },
    {
      name: "Ryan Gravenberch",
      match: "Liverpool v Brentford",
      first: [["12", "1"]],
      anytime: [["5", "1"]],
      last: [["12", "1"]],
      two_or_more: [["40", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["17", "2"]],
    },
    {
      name: "Trent Alexander-Arnold",
      match: "Liverpool v Brentford",
      first: [["18", "1"]],
      anytime: [["15", "2"]],
      last: [["18", "1"]],
      two_or_more: [["70", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Virgil van Dijk",
      match: "Liverpool v Brentford",
      first: [["25", "1"]],
      anytime: [["8", "1"]],
      last: [["20", "1"]],
      two_or_more: [["80", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Luke Chambers",
      match: "Liverpool v Brentford",
      first: [["25", "1"]],
      anytime: [["11", "1"]],
      last: [["25", "1"]],
      two_or_more: [["125", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Konstantinos Tsimikas",
      match: "Liverpool v Brentford",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Joel Matip",
      match: "Liverpool v Brentford",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Ibrahima Konate",
      match: "Liverpool v Brentford",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Jarell Quansah",
      match: "Liverpool v Brentford",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Joseph Gomez",
      match: "Liverpool v Brentford",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Bryan Mbeumo",
      match: "Liverpool v Brentford",
      first: [["17", "2"]],
      anytime: [["12", "5"]],
      last: [["7", "1"]],
      two_or_more: [["14", "1"]],
      hattrick: [["70", "1"]],
      first_and_last: [["25", "1"]],
      first_or_last: [["9", "2"]],
    },
    {
      name: "Yoane Wissa",
      match: "Liverpool v Brentford",
      first: [["10", "1"]],
      anytime: [["29", "10"]],
      last: [["17", "2"]],
      two_or_more: [["18", "1"]],
      hattrick: [["100", "1"]],
      first_and_last: [["33", "1"]],
      first_or_last: [["5", "1"]],
    },
    {
      name: "Neal Maupay",
      match: "Liverpool v Brentford",
      first: [["10", "1"]],
      anytime: [["3", "1"]],
      last: [["17", "2"]],
      two_or_more: [["20", "1"]],
      hattrick: [["125", "1"]],
      first_and_last: [["33", "1"]],
      first_or_last: [["11", "2"]],
    },
    {
      name: "Keane Lewis-Potter",
      match: "Liverpool v Brentford",
      first: [["12", "1"]],
      anytime: [["5", "1"]],
      last: [["12", "1"]],
      two_or_more: [["40", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["17", "2"]],
    },
    {
      name: "Michael Olakigbe",
      match: "Liverpool v Brentford",
      first: [["12", "1"]],
      anytime: [["5", "1"]],
      last: [["12", "1"]],
      two_or_more: [["45", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Yegor Yarmolyuk",
      match: "Liverpool v Brentford",
      first: [["14", "1"]],
      anytime: [["11", "2"]],
      last: [["14", "1"]],
      two_or_more: [["45", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["55", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Mathias Jensen",
      match: "Liverpool v Brentford",
      first: [["16", "1"]],
      anytime: [["13", "2"]],
      last: [["16", "1"]],
      two_or_more: [["55", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["60", "1"]],
      first_or_last: [["11", "1"]],
    },
    {
      name: "Saman Ghoddos",
      match: "Liverpool v Brentford",
      first: [["18", "1"]],
      anytime: [["15", "2"]],
      last: [["18", "1"]],
      two_or_more: [["65", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["66", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Ethan Brierley",
      match: "Liverpool v Brentford",
      first: [["22", "1"]],
      anytime: [["9", "1"]],
      last: [["22", "1"]],
      two_or_more: [["100", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Shandon Baptiste",
      match: "Liverpool v Brentford",
      first: [["22", "1"]],
      anytime: [["9", "1"]],
      last: [["22", "1"]],
      two_or_more: [["100", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Vitaly Janelt",
      match: "Liverpool v Brentford",
      first: [["22", "1"]],
      anytime: [["10", "1"]],
      last: [["22", "1"]],
      two_or_more: [["100", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Frank Onyeka",
      match: "Liverpool v Brentford",
      first: [["22", "1"]],
      anytime: [["9", "1"]],
      last: [["22", "1"]],
      two_or_more: [["100", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Christian Norgaard",
      match: "Liverpool v Brentford",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Ben Mee",
      match: "Liverpool v Brentford",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Nathan Collins",
      match: "Liverpool v Brentford",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Ethan Pinnock",
      match: "Liverpool v Brentford",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Val Adedokun",
      match: "Liverpool v Brentford",
      first: [["40", "1"]],
      anytime: [["16", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Mads Roerslev Rasmussen",
      match: "Liverpool v Brentford",
      first: [["40", "1"]],
      anytime: [["16", "1"]],
      last: [["40", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Mathias Jorgensen",
      match: "Liverpool v Brentford",
      first: [["40", "1"]],
      anytime: [["14", "1"]],
      last: [["40", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Kristoffer Ajer",
      match: "Liverpool v Brentford",
      first: [["40", "1"]],
      anytime: [["14", "1"]],
      last: [["40", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Kim Ji-soo",
      match: "Liverpool v Brentford",
      first: [["50", "1"]],
      anytime: [["16", "1"]],
      last: [["50", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["200", "1"]],
      first_or_last: [["25", "1"]],
    },
    { name: "No Goalscorer", first: ["14", "1"] },
  ],
  [
    {
      name: "Jarrod Bowen",
      match: "West Ham v Nottingham Forest",
      first: [["11", "2"]],
      anytime: [["9", "5"]],
      last: [["5", "1"]],
      two_or_more: [["11", "1"]],
      hattrick: [["45", "1"]],
      first_and_last: [["14", "1"]],
      first_or_last: [["14", "5"]],
    },
    {
      name: "Danny Ings",
      match: "West Ham v Nottingham Forest",
      first: [["6", "1"]],
      anytime: [["23", "10"]],
      last: [["6", "1"]],
      two_or_more: [["14", "1"]],
      hattrick: [["70", "1"]],
      first_and_last: [["18", "1"]],
      first_or_last: [["15", "4"]],
    },
    {
      name: "Divin Mubama",
      match: "West Ham v Nottingham Forest",
      first: [["13", "2"]],
      anytime: [["12", "5"]],
      last: [["13", "2"]],
      two_or_more: [["14", "1"]],
      hattrick: [["70", "1"]],
      first_and_last: [["18", "1"]],
      first_or_last: [["19", "5"]],
    },
    {
      name: "Mohammed Kudus",
      match: "West Ham v Nottingham Forest",
      first: [["7", "1"]],
      anytime: [["23", "10"]],
      last: [["6", "1"]],
      two_or_more: [["14", "1"]],
      hattrick: [["70", "1"]],
      first_and_last: [["18", "1"]],
      first_or_last: [["15", "4"]],
    },
    {
      name: "Michail Antonio",
      match: "West Ham v Nottingham Forest",
      first: [["15", "2"]],
      anytime: [["23", "10"]],
      last: [["6", "1"]],
      two_or_more: [["14", "1"]],
      hattrick: [["70", "1"]],
      first_and_last: [["18", "1"]],
      first_or_last: [["15", "4"]],
    },
    {
      name: "Said Benrahma",
      match: "West Ham v Nottingham Forest",
      first: [["8", "1"]],
      anytime: [["10", "3"]],
      last: [["8", "1"]],
      two_or_more: [["22", "1"]],
      hattrick: [["150", "1"]],
      first_and_last: [["25", "1"]],
      first_or_last: [["5", "1"]],
    },
    {
      name: "James Ward-Prowse",
      match: "West Ham v Nottingham Forest",
      first: [["8", "1"]],
      anytime: [["11", "4"]],
      last: [["7", "1"]],
      two_or_more: [["18", "1"]],
      hattrick: [["100", "1"]],
      first_and_last: [["20", "1"]],
      first_or_last: [["9", "2"]],
    },
    {
      name: "Maxwel Cornet",
      match: "West Ham v Nottingham Forest",
      first: [["17", "2"]],
      anytime: [["18", "5"]],
      last: [["17", "2"]],
      two_or_more: [["25", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["25", "1"]],
      first_or_last: [["11", "2"]],
    },
    {
      name: "Lucas Paqueta",
      match: "West Ham v Nottingham Forest",
      first: [["9", "1"]],
      anytime: [["19", "5"]],
      last: [["9", "1"]],
      two_or_more: [["28", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["28", "1"]],
      first_or_last: [["6", "1"]],
    },
    {
      name: "Pablo Fornals",
      match: "West Ham v Nottingham Forest",
      first: [["11", "1"]],
      anytime: [["11", "2"]],
      last: [["11", "1"]],
      two_or_more: [["45", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["8", "1"]],
    },
    {
      name: "Tomas Soucek",
      match: "West Ham v Nottingham Forest",
      first: [["12", "1"]],
      anytime: [["6", "1"]],
      last: [["12", "1"]],
      two_or_more: [["50", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Dan Chesters",
      match: "West Ham v Nottingham Forest",
      first: [["16", "1"]],
      anytime: [["8", "1"]],
      last: [["16", "1"]],
      two_or_more: [["80", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Conor Coventry",
      match: "West Ham v Nottingham Forest",
      first: [["16", "1"]],
      anytime: [["8", "1"]],
      last: [["16", "1"]],
      two_or_more: [["80", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Edson Alvarez",
      match: "West Ham v Nottingham Forest",
      first: [["18", "1"]],
      anytime: [["17", "2"]],
      last: [["18", "1"]],
      two_or_more: [["90", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["55", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Nayef Aguerd",
      match: "West Ham v Nottingham Forest",
      first: [["20", "1"]],
      anytime: [["10", "1"]],
      last: [["20", "1"]],
      two_or_more: [["100", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["60", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Konstantinos Mavropanos",
      match: "West Ham v Nottingham Forest",
      first: [["25", "1"]],
      anytime: [["12", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Angelo Ogbonna",
      match: "West Ham v Nottingham Forest",
      first: [["25", "1"]],
      anytime: [["12", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Kurt Zouma",
      match: "West Ham v Nottingham Forest",
      first: [["25", "1"]],
      anytime: [["11", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Aaron Cresswell",
      match: "West Ham v Nottingham Forest",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Ben Johnson",
      match: "West Ham v Nottingham Forest",
      first: [["33", "1"]],
      anytime: [["16", "1"]],
      last: [["33", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Thilo Kehrer",
      match: "West Ham v Nottingham Forest",
      first: [["40", "1"]],
      anytime: [["18", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Emerson Palmieri",
      match: "West Ham v Nottingham Forest",
      first: [["40", "1"]],
      anytime: [["18", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Vladimir Coufal",
      match: "West Ham v Nottingham Forest",
      first: [["50", "1"]],
      anytime: [["22", "1"]],
      last: [["50", "1"]],
      two_or_more: [["300", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["33", "1"]],
    },
    {
      name: "Taiwo Awoniyi",
      match: "West Ham v Nottingham Forest",
      first: [["7", "1"]],
      anytime: [["5", "2"]],
      last: [["13", "2"]],
      two_or_more: [["16", "1"]],
      hattrick: [["80", "1"]],
      first_and_last: [["18", "1"]],
      first_or_last: [["4", "1"]],
    },
    {
      name: "Morgan Gibbs-White",
      match: "West Ham v Nottingham Forest",
      first: [["10", "1"]],
      anytime: [["9", "2"]],
      last: [["10", "1"]],
      two_or_more: [["35", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["33", "1"]],
      first_or_last: [["7", "1"]],
    },
    {
      name: "Anthony Elanga",
      match: "West Ham v Nottingham Forest",
      first: [["10", "1"]],
      anytime: [["10", "3"]],
      last: [["8", "1"]],
      two_or_more: [["22", "1"]],
      hattrick: [["150", "1"]],
      first_and_last: [["25", "1"]],
      first_or_last: [["5", "1"]],
    },
    {
      name: "Brandon Aguilera",
      match: "West Ham v Nottingham Forest",
      first: [["11", "1"]],
      anytime: [["5", "1"]],
      last: [["11", "1"]],
      two_or_more: [["40", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["8", "1"]],
    },
    {
      name: "Nicolas Dominguez",
      match: "West Ham v Nottingham Forest",
      first: [["11", "1"]],
      anytime: [["24", "5"]],
      last: [["11", "1"]],
      two_or_more: [["40", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["35", "1"]],
      first_or_last: [["15", "2"]],
    },
    {
      name: "Andrey Santos",
      match: "West Ham v Nottingham Forest",
      first: [["14", "1"]],
      anytime: [["7", "1"]],
      last: [["14", "1"]],
      two_or_more: [["55", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["10", "1"]],
    },
    {
      name: "Danilo",
      match: "West Ham v Nottingham Forest",
      first: [["14", "1"]],
      anytime: [["13", "2"]],
      last: [["14", "1"]],
      two_or_more: [["55", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Ibrahim Sangare",
      match: "West Ham v Nottingham Forest",
      first: [["16", "1"]],
      anytime: [["15", "2"]],
      last: [["16", "1"]],
      two_or_more: [["70", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["11", "1"]],
    },
    {
      name: "Ryan Yates",
      match: "West Ham v Nottingham Forest",
      first: [["18", "1"]],
      anytime: [["17", "2"]],
      last: [["18", "1"]],
      two_or_more: [["90", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["55", "1"]],
      first_or_last: [["12", "1"]],
    },
    {
      name: "Nuno Tavares",
      match: "West Ham v Nottingham Forest",
      first: [["25", "1"]],
      anytime: [["11", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Orel Mangala",
      match: "West Ham v Nottingham Forest",
      first: [["25", "1"]],
      anytime: [["11", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Willy Boly",
      match: "West Ham v Nottingham Forest",
      first: [["25", "1"]],
      anytime: [["12", "1"]],
      last: [["25", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Neco Williams",
      match: "West Ham v Nottingham Forest",
      first: [["28", "1"]],
      anytime: [["14", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Murillo",
      match: "West Ham v Nottingham Forest",
      first: [["28", "1"]],
      anytime: [["12", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Harry Toffolo",
      match: "West Ham v Nottingham Forest",
      first: [["28", "1"]],
      anytime: [["14", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["80", "1"]],
      first_or_last: [["18", "1"]],
    },
    {
      name: "Moussa Niakhate",
      match: "West Ham v Nottingham Forest",
      first: [["33", "1"]],
      anytime: [["16", "1"]],
      last: [["33", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Cheikhou Kouyate",
      match: "West Ham v Nottingham Forest",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Scott McKenna",
      match: "West Ham v Nottingham Forest",
      first: [["33", "1"]],
      anytime: [["16", "1"]],
      last: [["33", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Serge Aurier",
      match: "West Ham v Nottingham Forest",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Joe Worrall",
      match: "West Ham v Nottingham Forest",
      first: [["40", "1"]],
      anytime: [["16", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Ola Aina",
      match: "West Ham v Nottingham Forest",
      first: [["40", "1"]],
      anytime: [["16", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["25", "1"]],
    },
    { name: "No Goalscorer", first: ["8", "1"] },
  ],
  [
    {
      name: "Armando Broja",
      match: "Chelsea v Man City",
      first: [["8", "1"]],
      anytime: [["10", "3"]],
      last: [["8", "1"]],
      two_or_more: [["22", "1"]],
      hattrick: [["150", "1"]],
      first_and_last: [["22", "1"]],
      first_or_last: [["5", "1"]],
    },
    {
      name: "Nicolas Jackson",
      match: "Chelsea v Man City",
      first: [["17", "2"]],
      anytime: [["16", "5"]],
      last: [["8", "1"]],
      two_or_more: [["22", "1"]],
      hattrick: [["150", "1"]],
      first_and_last: [["22", "1"]],
      first_or_last: [["5", "1"]],
    },
    {
      name: "Deivid Washington",
      match: "Chelsea v Man City",
      first: [["9", "1"]],
      anytime: [["4", "1"]],
      last: [["9", "1"]],
      two_or_more: [["33", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["28", "1"]],
      first_or_last: [["13", "2"]],
    },
    {
      name: "Cole Palmer",
      match: "Chelsea v Man City",
      first: [["9", "1"]],
      anytime: [["4", "1"]],
      last: [["9", "1"]],
      two_or_more: [["28", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["28", "1"]],
      first_or_last: [["13", "2"]],
    },
    {
      name: "Raheem Sterling",
      match: "Chelsea v Man City",
      first: [["9", "1"]],
      anytime: [["7", "2"]],
      last: [["17", "2"]],
      two_or_more: [["25", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["25", "1"]],
      first_or_last: [["11", "2"]],
    },
    {
      name: "Noni Madueke",
      match: "Chelsea v Man City",
      first: [["11", "1"]],
      anytime: [["5", "1"]],
      last: [["11", "1"]],
      two_or_more: [["40", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["35", "1"]],
      first_or_last: [["8", "1"]],
    },
    {
      name: "Mykhaylo Mudryk",
      match: "Chelsea v Man City",
      first: [["12", "1"]],
      anytime: [["24", "5"]],
      last: [["11", "1"]],
      two_or_more: [["40", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["35", "1"]],
      first_or_last: [["15", "2"]],
    },
    {
      name: "Alex Matos",
      match: "Chelsea v Man City",
      first: [["12", "1"]],
      anytime: [["13", "2"]],
      last: [["12", "1"]],
      two_or_more: [["50", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Conor Gallagher",
      match: "Chelsea v Man City",
      first: [["16", "1"]],
      anytime: [["15", "2"]],
      last: [["16", "1"]],
      two_or_more: [["70", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["50", "1"]],
      first_or_last: [["11", "1"]],
    },
    {
      name: "Enzo Fernandez",
      match: "Chelsea v Man City",
      first: [["20", "1"]],
      anytime: [["10", "1"]],
      last: [["20", "1"]],
      two_or_more: [["100", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["60", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Ian Maatsen",
      match: "Chelsea v Man City",
      first: [["22", "1"]],
      anytime: [["11", "1"]],
      last: [["22", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["66", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Reece James",
      match: "Chelsea v Man City",
      first: [["22", "1"]],
      anytime: [["10", "1"]],
      last: [["22", "1"]],
      two_or_more: [["125", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["60", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Moises Caicedo",
      match: "Chelsea v Man City",
      first: [["28", "1"]],
      anytime: [["14", "1"]],
      last: [["28", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Lesley Ugochukwu",
      match: "Chelsea v Man City",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Levi Colwill",
      match: "Chelsea v Man City",
      first: [["40", "1"]],
      anytime: [["18", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Benoit Badiashile",
      match: "Chelsea v Man City",
      first: [["40", "1"]],
      anytime: [["18", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Thiago Silva",
      match: "Chelsea v Man City",
      first: [["40", "1"]],
      anytime: [["18", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Malo Gusto",
      match: "Chelsea v Man City",
      first: [["40", "1"]],
      anytime: [["18", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["125", "1"]],
      first_or_last: [["25", "1"]],
    },
    {
      name: "Axel Disasi",
      match: "Chelsea v Man City",
      first: [["40", "1"]],
      anytime: [["16", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Marc Cucurella",
      match: "Chelsea v Man City",
      first: [["50", "1"]],
      anytime: [["22", "1"]],
      last: [["50", "1"]],
      two_or_more: [["400", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["35", "1"]],
    },
    {
      name: "Erling Haaland",
      match: "Chelsea v Man City",
      first: [["3", "1"]],
      anytime: [["17", "20"]],
      last: [["14", "5"]],
      two_or_more: [["9", "2"]],
      hattrick: [["16", "1"]],
      first_and_last: [["15", "2"]],
      first_or_last: [["29", "20"]],
    },
    {
      name: "Julian Alvarez",
      match: "Chelsea v Man City",
      first: [["6", "1"]],
      anytime: [["21", "10"]],
      last: [["11", "2"]],
      two_or_more: [["12", "1"]],
      hattrick: [["55", "1"]],
      first_and_last: [["16", "1"]],
      first_or_last: [["16", "5"]],
    },
    {
      name: "Jeremy Doku",
      match: "Chelsea v Man City",
      first: [["17", "2"]],
      anytime: [["3", "1"]],
      last: [["15", "2"]],
      two_or_more: [["20", "1"]],
      hattrick: [["125", "1"]],
      first_and_last: [["22", "1"]],
      first_or_last: [["24", "5"]],
    },
    {
      name: "Phil Foden",
      match: "Chelsea v Man City",
      first: [["17", "2"]],
      anytime: [["3", "1"]],
      last: [["15", "2"]],
      two_or_more: [["18", "1"]],
      hattrick: [["125", "1"]],
      first_and_last: [["22", "1"]],
      first_or_last: [["9", "2"]],
    },
    {
      name: "Oscar Bobb",
      match: "Chelsea v Man City",
      first: [["17", "2"]],
      anytime: [["18", "5"]],
      last: [["17", "2"]],
      two_or_more: [["25", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["25", "1"]],
      first_or_last: [["11", "2"]],
    },
    {
      name: "Bernardo Silva",
      match: "Chelsea v Man City",
      first: [["10", "1"]],
      anytime: [["24", "5"]],
      last: [["10", "1"]],
      two_or_more: [["40", "1"]],
      hattrick: [["250", "1"]],
      first_and_last: [["33", "1"]],
      first_or_last: [["7", "1"]],
    },
    {
      name: "Jack Grealish",
      match: "Chelsea v Man City",
      first: [["10", "1"]],
      anytime: [["19", "5"]],
      last: [["9", "1"]],
      two_or_more: [["28", "1"]],
      hattrick: [["200", "1"]],
      first_and_last: [["28", "1"]],
      first_or_last: [["6", "1"]],
    },
    {
      name: "Matheus Nunes",
      match: "Chelsea v Man City",
      first: [["12", "1"]],
      anytime: [["6", "1"]],
      last: [["12", "1"]],
      two_or_more: [["50", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Rodri",
      match: "Chelsea v Man City",
      first: [["12", "1"]],
      anytime: [["6", "1"]],
      last: [["12", "1"]],
      two_or_more: [["50", "1"]],
      hattrick: [["300", "1"]],
      first_and_last: [["40", "1"]],
      first_or_last: [["9", "1"]],
    },
    {
      name: "Mateo Kovacic",
      match: "Chelsea v Man City",
      first: [["14", "1"]],
      anytime: [["7", "1"]],
      last: [["14", "1"]],
      two_or_more: [["55", "1"]],
      hattrick: [["400", "1"]],
      first_and_last: [["45", "1"]],
      first_or_last: [["10", "1"]],
    },
    {
      name: "Rico Lewis",
      match: "Chelsea v Man City",
      first: [["22", "1"]],
      anytime: [["11", "1"]],
      last: [["22", "1"]],
      two_or_more: [["125", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["65", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "John Stones",
      match: "Chelsea v Man City",
      first: [["22", "1"]],
      anytime: [["11", "1"]],
      last: [["22", "1"]],
      two_or_more: [["125", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["66", "1"]],
      first_or_last: [["14", "1"]],
    },
    {
      name: "Kalvin Phillips",
      match: "Chelsea v Man City",
      first: [["25", "1"]],
      anytime: [["12", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Nathan Ake",
      match: "Chelsea v Man City",
      first: [["25", "1"]],
      anytime: [["12", "1"]],
      last: [["25", "1"]],
      two_or_more: [["150", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["70", "1"]],
      first_or_last: [["16", "1"]],
    },
    {
      name: "Ruben Dias",
      match: "Chelsea v Man City",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Josko Gvardiol",
      match: "Chelsea v Man City",
      first: [["33", "1"]],
      anytime: [["14", "1"]],
      last: [["33", "1"]],
      two_or_more: [["200", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["90", "1"]],
      first_or_last: [["20", "1"]],
    },
    {
      name: "Manuel Akanji",
      match: "Chelsea v Man City",
      first: [["40", "1"]],
      anytime: [["16", "1"]],
      last: [["40", "1"]],
      two_or_more: [["250", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["100", "1"]],
      first_or_last: [["22", "1"]],
    },
    {
      name: "Kyle Walker",
      match: "Chelsea v Man City",
      first: [["50", "1"]],
      anytime: [["20", "1"]],
      last: [["50", "1"]],
      two_or_more: [["300", "1"]],
      hattrick: [["500", "1"]],
      first_and_last: [["150", "1"]],
      first_or_last: [["28", "1"]],
    },
    { name: "No Goalscorer", first: ["15", "2"] },
  ],
];

var b = [
  [
    "Aston Villa v Fulham",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29359800/aston-villa-vs-fulham",
  ],
  [
    "Brighton v Sheffield Utd",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29359786/brighton-vs-sheffield-utd",
  ],
  [
    "Liverpool v Brentford",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29359798/liverpool-vs-brentford",
  ],
  [
    "West Ham v Nottingham Forest",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29359795/west-ham-vs-nottingham-forest",
  ],
  [
    "Chelsea v Man City",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29359791/chelsea-vs-man-city",
  ],
  [
    "Man City v Liverpool",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434061/man-city-vs-liverpool",
  ],
  [
    "Burnley v West Ham",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434056/burnley-vs-west-ham",
  ],
  [
    "Luton v Crystal Palace",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434055/luton-vs-crystal-palace",
  ],
  [
    "Newcastle v Chelsea",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434054/newcastle-vs-chelsea",
  ],
  [
    "Nottingham Forest v Brighton",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434057/nottingham-forest-vs-brighton",
  ],
  [
    "Sheffield Utd v Bournemouth",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434058/sheffield-utd-vs-bournemouth",
  ],
  [
    "Brentford v Arsenal",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434053/brentford-vs-arsenal",
  ],
  [
    "Tottenham v Aston Villa",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434059/tottenham-vs-aston-villa",
  ],
  [
    "Everton v Man Utd",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434060/everton-vs-man-utd",
  ],
  [
    "Fulham v Wolves",
    "https://sports.williamhill.com/betting/en-gb/football/OB_EV29434062/fulham-vs-wolves",
  ],
];


var sportingIndex = [
    {
        "match": "Arsenal v Wolves",
        "sell_buy": "1.75 - 1.95"
    },
    {
        "match": "Brentford v Luton",
        "sell_buy": "1 - 1.2"
    },
    {
        "match": "Burnley v Sheff Utd",
        "sell_buy": "0.65 - 0.85"
    },
    {
        "match": "Nottingham Forest v Everton",
        "sell_buy": "0 - 0.2"
    },
    {
        "match": "Newcastle v Man Utd",
        "sell_buy": "0.35 - 0.55"
    },
    {
        "match": "Bournemouth v Aston Villa",
        "sell_buy": "0.3 - 0.5"
    },
    {
        "match": "Chelsea v Brighton",
        "sell_buy": "0.7 - 0.9"
    },
    {
        "match": "Liverpool v Fulham",
        "sell_buy": "1.75 - 1.95"
    },
    {
        "match": "West Ham v Crystal Palace",
        "sell_buy": "0.35 - 0.55"
    },
    {
        "match": "Man City v Tottenham",
        "sell_buy": "1.8 - 2"
    }
]